name: build and deploy


on:
  push:


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Nochmal schauen
        run:  |
          ls

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: add nodejs dependencies and build
        run:  |
          npm clean-install
          npm run build

