name: build and deploy


on:
  push:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout
        uses: actions/checkout@v4

      - name: Nochmal schauen
        run:  |
          ls

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: add nodejs dependencies and build
        run:  |
          npm clean-install
          npm run build

      - name: list files
        run:  |
          ls -R dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with: 
          name: mysite
          path: dist
          retentions-days: 3

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build

    steps:  
      - name: Download artifact
        uses: actions/download-artifact@v4
        with: 
          name: mysite
          path: dist

      - name: view files
        run:  |
          ls -R dist/

      - name: view credentials 
        run: |
          echo "${{ vars.BUCKET_NAME}}"
          echo "${{ secrets.AWS_ACCESS_KEY_ID}}"
          echo "${{ secrets.AWS_SECRET_ACCESS_KEY}}"                    