name: build and deploy


on:
  push:


jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      -  name: Mal schauen
         run:  |
           echo "Hallo!"
           ls
      
      - name:  Checkout
        uses: actions/checkout@v4

      - name: Nochmal schauen
        run:  |
          ls
